"""impl() - Implements a plan generated by pride.

Takes a plan (from a previous pride() call) and executes it,
making actual code changes.
"""

import subprocess
import time
from ..memory import MemoryEntry
from ..display import Display
from ..context.parser import extract_sections


def _get_git_status_snapshot(cwd: str) -> set[str]:
    """Get a snapshot of currently modified files in git working tree.

    Returns a set of (status, filepath) tuples for diff calculation.
    Returns empty set if not in a git repo or on error.
    """
    try:
        result = subprocess.run(
            ["git", "status", "--porcelain"],
            cwd=cwd,
            capture_output=True,
            text=True,
            timeout=10,
        )
        if result.returncode != 0:
            return set()

        files = set()
        for line in result.stdout.strip().split("\n"):
            if not line:
                continue
            # Format: XY filename or XY "filename" for paths with spaces
            status = line[:2]
            filepath = line[3:].strip().strip('"')
            files.add((status, filepath))

        return files
    except Exception:
        return set()


def _extract_files_changed(before_snapshot: set[str], after_snapshot: set[str]) -> list[str]:
    """Extract list of files changed by implementation by comparing snapshots.

    Compares before/after git status snapshots to isolate only files
    that were actually modified by the implementation, not pre-existing changes.

    Args:
        before_snapshot: Git status snapshot from before implementation
        after_snapshot: Git status snapshot from after implementation

    Returns:
        List of filepaths that were newly modified or had their status change.
    """
    # Files that are new or have changed status
    new_or_changed = after_snapshot - before_snapshot

    # Extract just the filepaths (second element of tuple)
    files = []
    for status, filepath in new_or_changed:
        # Skip untracked files (??), we only want tracked changes
        if status.strip() != "??":
            files.append(filepath)

    return files

IMPLEMENT_PROMPT = """Implement this plan completely.

OVERALL GOAL: {prompt}

PLAN:
{plan}

DELIBERATION CONTEXT:
{deliberation_summary}

Make all the actual code changes. Create and edit files as needed.
Be thorough and implement the full plan. Follow the PLAN above closely.
If the PLAN seems incomplete, use the DELIBERATION CONTEXT for guidance."""


def _build_implement_context(memory, max_chars=5000):
    """Build focused context for implementer - only decisions + warnings.

    The converge plan already contains the full approach. The implementer
    only needs additional context about hard constraints and warnings
    that MUST be respected.
    """
    entries = memory.read_all()
    parts = []

    for e in entries:
        if e.type == "decision":
            parts.append(f"Decision: {e.content[:2000]}")
        elif e.phase == "propose" and e.content:
            sections = extract_sections(e.content)
            warnings = sections.get("warnings", "")
            if warnings:
                agent_label = e.agent or "agent"
                parts.append(f"{agent_label} warnings: {warnings[:500]}")

    result = "\n\n".join(parts)
    return result[:max_chars] if result else "(no additional context)"


def execute_impl(prompt, previous, step, memory, config, cwd, cost_manager=None):
    """Implement the converged plan by writing files."""
    if not previous or not previous.get("plan"):
        return {
            "success": False,
            "error": "No plan found from previous step to implement.",
        }

    plan = previous["plan"]
    # Assuming lead_agent can be retrieved from config or passed somehow,
    # or that a default implementer agent is used. For now, let's assume
    # the provider logic is handled internally by a default.
    # TODO: Refactor to pass agent explicitly or determine from config
    default_provider_name = config.get("providers", {}).get("default", "claude")
    implementer_agent = config.get("lion_system_agent", None)
    if implementer_agent is None:
        from ..providers import get_provider
        implementer_agent = get_provider(default_provider_name, config)


    # Build focused context (decisions + warnings only, not full dump)
    deliberation_summary = _build_implement_context(memory)

    impl_prompt = IMPLEMENT_PROMPT.format(
        prompt=prompt,
        plan=plan,
        deliberation_summary=deliberation_summary,
    )

    Display.phase("implement", "Building the solution...")

    # Capture git status BEFORE implementation to isolate changes
    before_snapshot = _get_git_status_snapshot(cwd)

    result = implementer_agent.implement(impl_prompt, cwd)

    # Capture git status AFTER implementation
    after_snapshot = _get_git_status_snapshot(cwd)

    if not result.success:
        Display.step_error("implement", result.error or "Implementation failed")

    memory.write(MemoryEntry(
        timestamp=time.time(),
        phase="implement",
        agent="implementer",
        type="code",
        content=result.content or "",
        metadata={"model": result.model},
    ))

    # Extract files changed by this implementation (diff of before/after snapshots)
    # This isolates only files changed by impl, not pre-existing working tree changes
    files_changed = _extract_files_changed(before_snapshot, after_snapshot)

    return {
        "success": result.success,
        "code": result.content or "",
        "files_changed": files_changed,
        "tokens_used": result.tokens_used,
    }
